# Installing httpd on target hosts
-
    name: Playbook to install and start httpd via yum and service command
    hosts: all
    tasks:
        -  name: Install httpd
           yum: name=httpd update_cache=yes state=present
           become: yes

        -  name: Start service httpd
           service: name=httpd enabled=yes state=started
           become: yes

        - name: To check if service status is running or not
          become: true
          service: service httpd status
