      - name: Copy and install mysql via rpm
        yum:
            name: https://repo.mysql.com/mysql80-community-release-el7-1.noarch.rpm
            state: present
        become: true
        tags: ['install']

      - name: yum install mysql packages and repo
        yum:
          name: mysql-community-server
          enablerepo: mysql80-community
        become: true
        tags: ['install']

      - name: start mysql service
        service: name=mysqld state=started enabled=yes
        tags: ['service']
        become: true

      - name: create database
        mysql_db:
          name: "{{mysql_db_name}}" 
          state: present
          login_host: localhost
          login_port: "{{ mysql_port }}"
          login_user: "{{ mysql_root }}"
          login_password: "{{ mysql_root_pass }}"
        tags: ['database_creation']
        become: true
