# Installing httpd on target hosts
-
    name: Playbook to install apache2 and other packages
    hosts: all
    tasks:
        -
          # Here nginx on Amazon Linux is not installed via yum
          name : Install nginx via command line
          command: amazon-linux-extras install nginx1.12
          become: true
