# Installing httpd on target hosts
-
    name: Playbook to install httpd
    hosts: all
    tasks:
        -
           name: Install httpd
           yum:
             name: httpd
             state: installed
           become: true
 
