# Installing httpd on target hosts
-
    name: Playbook to install mysql via rpm
    hosts: all
    tasks:
      - name: Copy and install mysql via rpm
        yum:
            name: https://repo.mysql.com/mysql80-community-release-el7-1.noarch.rpm
            state: present
        become: true

      - name: yum install mysql packages and repo
        yum:
          name: mysql-community-server
          enablerepo: mysql80-community
        become: true
